name: CI Minishish

on:
  push:
    branches: [ main, stage, dev ]
  pull_request:
    branches: [ main ]

# Evita build duplicate su rapidi aggiornamenti
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build (Makefile)
    runs-on: ubuntu-latest

    steps:
    
    # Scarica repo
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Installa strumenti (gcc, make e librerie base)
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    # Verifica sintassi del Makefile senza compilare
    - name: Makefile sanity check
      run: make --dry-run
      
    # Compila make
    - name: Build
      run: make
      
    # Runna i test
    - name: Run tests
      run: make test